# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SwisstopoGeocoder
                                 A QGIS plugin
 This is a process designed to provide geocoding functionality using the SwissTopo geocoding service.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-11-17
        copyright            : (C) 2023 by Geometa Lab
        email                : geometalab@ost.ch
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Geometa Lab'
__date__ = '2023-11-17'
__copyright__ = '(C) 2023 by Geometa Lab'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SwisstopoGeocoder class from file SwisstopoGeocoder.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .swisstopo_geocoder import SwisstopoGeocoderPlugin
    return SwisstopoGeocoderPlugin()
