# -*- coding: utf-8 -*-

"""
/***************************************************************************
 geocoder
                                 A QGIS plugin
 SwissTopoGeocoderProcess
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-11-09
        copyright            : (C) 2023 by Nukufel
        email                : Nukufel
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Nukufel'
__date__ = '2023-11-09'
__copyright__ = '(C) 2023 by Nukufel'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'
from qgis.core import QgsProject, QgsPointXY, QgsVectorLayer, QgsField, QgsGeometry, QgsFeature, QgsProcessingFeedback
from PyQt5.QtCore import QVariant
from qgis.utils import iface
import requests
import time
import threading

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterField,
                       QgsProcessingOutputMapLayer)


class geocoderAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    LAYER_INPUT = 'LAYER_INPUT'
    COLUMN_INPUT = 'COLUMN_INPUT'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.LAYER_INPUT,
                self.tr('Input layer'),
                [QgsProcessing.TypeFile]
            )
        )

        self.addParameter(
            QgsProcessingParameterField(
                self.COLUMN_INPUT,
                self.tr('Select an attribute'),
                parentLayerParameterName=self.LAYER_INPUT
            )
        )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).

        self.addOutput(
            QgsProcessingOutputMapLayer(
                self.OUTPUT,
                self.tr('Output layer')
            )
        )


    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

    # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsLayer(parameters, self.LAYER_INPUT, context)
        print(source.name())

        column_surce = self.parameterAsString(parameters, self.COLUMN_INPUT, context)
        print(column_surce)


        try:
            new_layer = self.define_layer(source.name(), column_surce, feedback)
            parameters[self.OUTPUT] = new_layer
            QgsProject.instance().addMapLayer(new_layer)
            print(new_layer)
        except Exception as e:
            print(e)



        # Compute the number of steps to display within the progress bar and
        # get features from source
        """total = 100.0 / source.featureCount() if source.featureCount() else 0
        features = source.getFeatures()

        for current, feature in enumerate(features):
            # Stop the algorithm if cancel button has been clicked
            if feedback.isCanceled():
                break


            # Update the progress bar
            feedback.setProgress(int(current * total))"""

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.

        return {self.OUTPUT: new_layer}
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'SwissTopoGeocoderProcess'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'SwissTopoGeocoderProcess'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return geocoderAlgorithm()



    @staticmethod
    def error_handling_user(type, msg):
        iface.messageBar().pushWarning(type, msg)

    @staticmethod
    def get_cords(address, fet, provider, new_layer):
        url = "https://api3.geo.admin.ch/rest/services/api/SearchServer?origins=address&type=locations&sr=2056&searchText="

        query = address  # You may need to format the address as needed

        response = requests.get(url + query)
        response_json = response.json()

        latitude = response_json['results'][0]['attrs']['lat']
        longitude = response_json['results'][0]['attrs']['lon']

        if latitude is not None and longitude is not None:
            point = QgsPointXY(float(longitude), float(latitude))
            fet.setGeometry(QgsGeometry.fromPointXY(point))

            fet.setAttributes([address, latitude, longitude])
            provider.addFeatures([fet])
            new_layer.updateExtents()
            new_layer.commitChanges()


    def define_layer(self, data_layer_name, address_col, feedback):
        try:
            layer = QgsProject.instance().mapLayersByName(data_layer_name)[0]
        except:
            print("Leyername does not exist.")
            return

        new_layer_name = "PointsLayer"
        new_layer = QgsVectorLayer("Point?crs=epsg:4326", new_layer_name, "memory")
        provider = new_layer.dataProvider()
        new_layer.startEditing()

        provider.addAttributes([QgsField("address", QVariant.String),
                                QgsField("lat", QVariant.Double),
                                QgsField("lon", QVariant.Double)])

        fet = QgsFeature()

        for feature in layer.getFeatures():
            if feedback.isCanceled():
                break
            try:
                address = feature[address_col]
                self.get_cords(address, fet, provider, new_layer)
            except:
                # give push msg
                print(address, 'failed')

            time.sleep(1)

        new_layer.commitChanges()

        #QgsProject.instance().addMapLayer(new_layer)
        #print("New point layer created and added to the map.")
        return new_layer

